/*
 * hal_touch.h
 *
 * Thin wrapper over FSP's Touch middleware (rm_touch), configured
 * entirely via QE for Capacitive Touch -- not standard Configurator
 * Properties (confirmed: there's no Callback field on the rm_touch
 * module itself, because QE already wires its own callback
 * internally when you run the CapTouch workflow).
 *
 * CORRECTED (round 2): g_qe_touch_instance_config01 and g_qe_touch_flag
 * are declared in qe_touch_config.h (generated by QE's "Output
 * Parameter Files" step), NOT hal_data.h.
 *
 * Rather than trying to override QE's internal callback (there's
 * nowhere exposed to do that), this HAL layer polls g_qe_touch_flag
 * directly -- the same signal QE's own sample code uses -- but with a
 * short yielding delay between checks instead of a raw busy-wait, so
 * it doesn't starve other FreeRTOS tasks.
 *
 * If you renamed the configuration in QE to something other than the
 * default "config01", update G_TOUCH_INSTANCE below to match.
 */

#ifndef HAL_TOUCH_H
#define HAL_TOUCH_H

#include "qe_touch_config.h"   /* QE-generated: g_qe_touch_instance_config01, g_qe_touch_flag */
#include <stdint.h>
#include <stdbool.h>

#define G_TOUCH_INSTANCE   (g_qe_touch_instance_config01)

/**
 * hal_touch_init
 * Opens the touch instance.
 */
void hal_touch_init(void);

/**
 * hal_touch_scan_and_wait
 * Starts a scan and polls g_qe_touch_flag (short yielding delay
 * between checks, not a busy-wait) until it's set or timeout_ms
 * elapses, then clears it.
 * @return  true if the scan completed within timeout_ms.
 */
bool hal_touch_scan_and_wait(uint32_t timeout_ms);

/**
 * hal_touch_get_button_status
 * Gets the current button status mask and slider position.
 *
 * @param[out] p_button_status   Pointer to store 64-bit button status mask
 * @param[out] p_slider_position Pointer to store 16-bit slider position (TOUCH_OFF_VALUE when not touched)
 * @return fsp_err_t             FSP_SUCCESS if data read succeeded.
 */
fsp_err_t hal_touch_get_button_status(uint64_t * p_button_status, uint16_t * p_slider_position);

#endif /* HAL_TOUCH_H */