/*
 * hal_flash.h
 *
 * Thin wrapper over FSP's r_flash_lp driver (g_flash0), configured for
 * Data Flash Background Operation (BGO) -- non-blocking by hardware,
 * with completion signaled via callback -> semaphore, same ISR-signal
 * pattern used elsewhere in this project (IR capture, UART RX, touch
 * scan-complete).
 *
 * BGO being enabled doesn't force every caller to be non-blocking --
 * this file exposes both start/wait primitives, and eeprom_driver.c
 * builds both a blocking and a non-blocking API on top of them.
 *
 * IMPORTANT: only ONE flash operation (write OR erase) can be in
 * flight at a time -- r_flash_lp returns an error if you start a
 * second one before the first completes. hal_flash itself does not
 * enforce this serialization; eeprom_driver.c does, via g_eeprom_mutex.
 * Do not call hal_flash_* functions directly from application code --
 * go through eeprom_driver.
 */

#ifndef HAL_FLASH_H
#define HAL_FLASH_H

#include "hal_data.h"   /* FSP-generated: g_flash0 instance, FLASH_DF_BLOCK_0,
                          * FLASH_DATA_BLOCK_SIZE (or whatever your generated
                          * project actually names these -- see the TODO in
                          * hal_flash.c; macro names are device/FSP-version
                          * specific and should be confirmed against your
                          * generated hal_data.h before trusting these).
                          */
#include <stdint.h>
#include <stdbool.h>

/**
 * hal_flash_init
 * Opens g_flash0. Call once, before any other hal_flash_* function.
 */
void hal_flash_init(void);

/**
 * hal_flash_write_start
 *
 * Initiates a write of num_bytes from src (RAM) to flash_address (data
 * flash). Returns immediately -- does NOT wait for completion.
 *
 * @return  true if the write was successfully STARTED (not that it's
 *          finished -- use hal_flash_wait_complete()/hal_flash_poll_complete()
 *          for that). false if r_flash_lp rejected the request (e.g. a
 *          previous operation is still in flight -- shouldn't happen if
 *          callers go through eeprom_driver's mutex correctly).
 */
bool hal_flash_write_start(uint32_t flash_address, const uint8_t *src, uint32_t num_bytes);

/**
 * hal_flash_erase_block_start
 *
 * Initiates an erase of num_blocks starting at flash_address (must be
 * block-aligned -- see FLASH_DATA_BLOCK_SIZE). Returns immediately.
 *
 * @return  true if the erase was successfully started.
 */
bool hal_flash_erase_block_start(uint32_t flash_address, uint32_t num_blocks);

/**
 * hal_flash_wait_complete
 *
 * Blocks (up to timeout_ms) until the most recently started write or
 * erase operation's completion callback fires.
 *
 * @return  true if completion was signaled within timeout_ms.
 */
bool hal_flash_wait_complete(uint32_t timeout_ms);

/**
 * hal_flash_poll_complete
 *
 * Non-blocking check: has the most recently started operation
 * completed since the last time this (or hal_flash_wait_complete) was
 * called successfully?
 *
 * @return  true if a completion is pending (and consumes it, same as
 *          hal_flash_wait_complete would) -- false if still in progress.
 */
bool hal_flash_poll_complete(void);

/**
 * hal_flash_read
 *
 * Data flash is memory-mapped for reads once DFLCTL is enabled (see
 * R_BSP_WarmStart -- this project already does this in the
 * BSP_WARM_START_RESET block, generated by default). A read is
 * therefore just a memcpy, not an FSP driver call -- always
 * synchronous, no non-blocking variant needed.
 */
void hal_flash_read(uint32_t flash_address, uint8_t *dst, uint32_t num_bytes);

#endif /* HAL_FLASH_H */